### ISSUE TITLE
Not working with 1.14

### ISSUE THREAD

**Issue by OverDhill** [Pecacheu/Elevators-v2#11]
No errors in log even with debug on but nothing is functioning.  This is one of my most needed plugins as it is such and awesome elevator. Please update

Using the latest Spigot

**Comment by Pecacheu** [comment]
Hi, I'm going to be getting back into plugin development and will update this plugin once I have time, but I have been quite busy lately.

**Comment by dretax** [comment]
I'll make an update for It. Standby for PR.

**Comment by dretax** [comment]
https://github.com/Pecacheu/Elevators-v2/pull/12

**Comment by DilanRona** [comment]
Same here, standing by for the update to 1.14.3. Cant wait to use the plugin again.

**Comment by OverDhill** [comment]
> 
> 
> Same here, standing by for the update to 1.14.3. Cant wait to use the plugin again.

It is actually working now that dretax has updated it. Look up a couple posts

**Comment by dretax** [comment]
#12

**Comment by Pecacheu** [comment]
Now working on 1.15.x!
