### ISSUE TITLE
Players gaining access to flying

### ISSUE THREAD

**Issue by mkirby** [Pecacheu/Elevators-v2#16]
I'm having issues in 1.15.2 where if elevator shafts don't have roofs then players are launched into the air when the elevator rises to the top floor. And if elevators do not have shaft walls then players can walk off the elevator platform while it's rising and can walk on air at that level. If you have an elytra then you can fly downwards and strangely bounce off the ground to keep flying around.

**Comment by Pecacheu** [comment]
Not able to recreate the launch into the air bug on 1.18.1 on latest version
But I can confirm that fly getting stuck on in survival if you leave the elevator while it's running is a bug. I'll look into that and the elytra thing.

**Comment by Pecacheu** [comment]
Oops forgot to mention issue in commit. This issue is also fixed with latest v3.3.3
