### ISSUE TITLE
Extremely horrible naming conventions in the Elevator object

### ISSUE THREAD

**Issue by nixxholas** [Pecacheu/Elevators-v2#17]
Before i continue suffering, can u explain to me whats sGroup and csGroup? What do they mean?

What's CSData?

It's okay to name it like that but there ain't comments

**Comment by Pecacheu** [comment]
Damn I can't believe I have issues on this dating two years back
I've been gone from Minecraft that long? Time flies :/

And yeah sorry about the bad code. My line formatting was AWFUL back then
I've managed to get it updated to Paper 1.18.1 now, build coming soon

Oh, and CSData stands for Call Sign Data btw :P
