### ISSUE TITLE
UTF-8 garbled characters

### ISSUE THREAD

**Issue by JPlayer3** [Pecacheu/Elevators-v2#18]
When I convert the characters to Japanese, the characters are garbled when reloading.

title: '&1[&3エレベーター&1]'
                     ↓
title: '&1[&3繧ｨ繝ｬ繝吶�ｼ繧ｿ繝ｼ&1]'

It was written below to use escape character instead of UTF-8, so I tried it but it doesn't work.

title: '&1[&3\u30A8\u30EC\u30D9\u30FC\u30BF\u30FC&1]'
![2020-11-01_16 16 05](https://user-images.githubusercontent.com/72402669/97797125-c81fde00-1c5d-11eb-94e8-a5a1d3587706.png)

Is it impossible to translate the hierarchy?

**Comment by Pecacheu** [comment]
That is really strange and I'm not sure why it does that, must be some obscure Java or Minecraft UTF-8 bug. Would definitely need some testing to narrow down which step of the process that happens in.

I will see if I can get to that... eventually
Or if someone else can figure out the issue and give a pull request, that's cool too

**Comment by JPlayer3** [comment]
I think "chcp 65001" would have avoided the garbled characters.
I haven't played recently, so I forget, but I think I was able to set it in Japanese.

**Comment by Pecacheu** [comment]
Let me know if this still happens, Minecraft has changed how it handles special characters over time so this may have resolved itself
