### ISSUE TITLE
1.18.2 Stops new elevators from being created

### ISSUE THREAD

**Issue by LXManiac** [Pecacheu/Elevators-v2#21]
Old elevators work fine but new ones cannot transfer sign to Elevators v2. Says no elevator detected.

**Comment by Pecacheu** [comment]
Which plugin version are you using?
Config file saving bug should've been fixed in v3.3.2

**Comment by LXManiac** [comment]
I'm using the latest version (3.3.2) but it still has an error sign. I tried it at different heights above y+0 and nothing. 
![Elevator Issue](https://user-images.githubusercontent.com/76850438/158916924-d5248860-e9b1-4b2b-bfb7-88cdedc8a4a3.jpg)
\

**Comment by Pecacheu** [comment]
That's super weird. Check the console though, the **> ERROR <** on the sign means that there was an internal Java error, otherwise the sign would show **[???]** if you created the elevator wrong in some way.

**Comment by Pecacheu** [comment]
Also I'm working on another big update with some new features and a lot of code optimization. So once that's done you can try that version. I seem to be able to create new elevators fine in the beta.

**Comment by LXManiac** [comment]
Here is the error in the console. Also really glad there is gonna be new features. Looking forward to it.
[Elevator Error.txt](https://github.com/Pecacheu/Elevators-v2/files/8308481/Elevator.Error.txt)

**Comment by Pecacheu** [comment]
Seems like the code was expecting the elevator sign data to be there, and when attempting to get the min/max height of the elevator shaft it tries to pull up a sign block that doesn't exist.

But the elevator creation and new sign column creation routines (yes you can have multiple elevator signs per floor, and they'll line up neatly) are some of the things I overhauled, so hopefully this has now been fixed, but we'll see
