### ISSUE TITLE
Plugin does not load

### ISSUE THREAD

**Issue by Jonnite** [Pecacheu/Elevators-v2#23]
I am using Aternos but the plugin does not seem to work.
I am using Spigot/Bukit 1.18.2 on aternos.

https://user-images.githubusercontent.com/92640192/163176380-5883aee4-ca31-499b-8d4b-eabf105f35d8.png
https://user-images.githubusercontent.com/92640192/163176457-86288e3a-c0df-49c0-84a7-b47a893a1044.png

**Comment by Pecacheu** [comment]
Whoops looks like I missed a bug report again haha.

Interesting, I've never heard of Aternos. Interestingly it seems like what it's erroring on is, while relatively new, a completely standard part of the Spigot/Paper/Bukkit API.

Not sure what could cause that other than using an older game version than I built it for, which isn't the case if you're using version 3.3.4 on 1.18.2. I can look at it closer later in the week, got a busy schedule rn.

**Comment by Pecacheu** [comment]
Upgrade to 1.21.3
