### ISSUE TITLE
Incompatibility with 1.19

### ISSUE THREAD

**Issue by LilianLem** [Pecacheu/Elevators-v2#24]
The plugin seems to be incompatible with 1.19, as you can see here with this log at server startup : https://pastebin.com/tTQErz4g

I'm running the first release of Spigot 1.19.

**Comment by LilianLem** [comment]
Elevators is now working with latest build of Paper 1.19. Either it works differently with Spigot, or something has been fixed in their code.

**Comment by Pecacheu** [comment]
Ah, interesting. It could be a Spigot incompatibility, but Spigot did work last I tested.

I compiled the plugin using the Paper API as it worked a bit better with Paper when I did so, but that should be backward compatible with Spigot as well. But it does figure that Paper would work best.

Backward compatibility stuff can get weird sometimes.
