### ISSUE TITLE
1.18.2 Paper calls work but lift wont move inside

### ISSUE THREAD

**Issue by vmo64** [Pecacheu/Elevators-v2#28]
Im using 1.18.2 paper and I can make lifts and call them to floors but when I'm inside the lift it will not move even if I select a floor, no errors or anything. What could be the issue?

**Comment by Runkang10** [comment]
Just click the iron block to start move in the floor that you selected.

**Comment by Pecacheu** [comment]
@Runkang10 is correct, you can click any block inside the elevator besides the sign to make it move.
