### ISSUE TITLE
Error while loading config

### ISSUE THREAD

**Issue by PrincePalm** [Pecacheu/Elevators-v2#3]
Im getting the same error as the closed issue, and im also using the latest version of spigot:

[Elevators] Error while loading config!
NOPATH

**Comment by Pecacheu** [comment]
Well, Spigot must not be creating the directory automatically when you install the plugin.
Elevators should detect that, and create it itself instead. So I don't know why it isn't. Probably a bug.

**Comment by Pecacheu** [comment]
Meanwhile, you can create the folder manually. Name it `Elevators`. Case sensitive.

**Comment by PrincePalm** [comment]
I've now created the folder, but im still getting the same error. What seems to be wrong here?

**Comment by Pecacheu** [comment]
In that case, the issue must be with the config saving rather than creating the folder. I'm working on a fix to the plugin now.

**Comment by Pecacheu** [comment]
Should be fixed in v3.1.1.

**Comment by PrincePalm** [comment]
Thanks, it works now
