### ISSUE TITLE
[BUG]: Outdated loop warning causes server degrading performance in 1.21.1

### ISSUE THREAD

**Issue by Runkang10** [Pecacheu/Elevators-v2#30]
The plugin started to having outdated problems with some bukkit modules:

![image](https://github.com/user-attachments/assets/b2d9c5ca-215f-48f2-ba05-ccd6a2eb4855)

**Comment by Pecacheu** [comment]
This should be fixed in the new release
Can't reproduce wioth latest paper builds for 1.21.X or 1.19.X
