### ISSUE TITLE
Flying while moving in the elevator

### ISSUE THREAD

**Issue by PrincePalm** [Pecacheu/Elevators-v2#4]
My friend used the elevator today. He tried to move while running it, and ended up flying around without able to jump or go back. So i had to delete his playerdata to make him normal again.

Here is a screenshot:
![2018-07-12_00 43 43](https://user-images.githubusercontent.com/32468152/42604423-f0f10068-8572-11e8-9998-958c294539a8.png)

**Comment by Pecacheu** [comment]
Yeah, it turns off player gravity to keep the server from kicking players for flying. Unfortunately, it's difficult to tell when a player gets stuck somehow. Using the elevator again usually gets you unstuck.

**Comment by Salzian** [comment]
Maybe just add an admin command to undo it in case this happens?

**Comment by Pecacheu** [comment]
That should help. I was thinking of adding a listener for if the player logs out while using the elevator, but I'm not sure how well that would work. Maybe I could store a list of entities in the elevator when it starts moving, and make sure they stay in.

**Comment by Pecacheu** [comment]
Oh forgot to close this one, solved this issue a few versions ago, if you left click the air it resets gravity for all entities in the elevator.
