### ISSUE TITLE
Door bug, removing plugin still has side-effects

### ISSUE THREAD

**Issue by rubenbarkman** [Pecacheu/Elevators-v2#9]
With the latest update the doors of all elevators started continuously opening and closing. As soon you entered the elevator you started flying upwards without doing anything. I was forced to remove the plugin, but now, players that entered the elevators still randomly start levitating in to the air. Even when the plugin is removed. Is any kind of fix in the works?

**Comment by Pecacheu** [comment]
Currently fixed, working on more bugfixes before next release
